# Generated by Django 4.0 on 2024-03-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darabala', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubs',
            options={'verbose_name_plural': 'Clubs'},
        ),
        migrations.AlterModelOptions(
            name='daycares',
            options={'verbose_name_plural': 'Daycares'},
        ),
        migrations.AlterModelOptions(
            name='parents',
            options={'verbose_name_plural': 'Parents'},
        ),
        migrations.AlterModelOptions(
            name='vouchers',
            options={'verbose_name_plural': 'Vouchers'},
        ),
    ]
